# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 7 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: adrienbrunet
google_analytics: UA-42192634-5
gems:
  - jemoji
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Adrien Brunet

description: Another Dev Blog
author:
  name: Adrien Brunet
  email: brunet.adrien@gmail.com
  github: adrienbrunet
  twitter: Adrien_Brunet
  linkedin: adrienbrunet
  bio: Dev and Beer Lover
  email_md5: 9165d0c82ff830e0c6d4535314c454ff

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
